add support for tables without borders
preservim/vim-markdown pull request #643
Opened 2023-09-22 00:09 UTC by gko

This seems like a valid table:
```
header 1|header 2
--|--
data 1|data 2
```

At least in github.

The solution in this pull request is to wrap all lines that don't have `|` at the beginning or the end of line.

I also added range call support. It doesn't change the implementation but allows to call `TableFormat` while having the selection.

2023-09-22 09:43 UTC, alerque requested changes
I'm happy to see support for table formats added, but I think we're going to need to have this gated behind a feature flag. We can discuss the merits of default on or off, but I know not all Markdown engines support this syntax and it has a high risk of false positive matches.

2023-09-23 07:39 UTC, gko commented
hey @alerque,

I added the flag `g:vim_markdown_borderless_table` and documented it.

Although I should point out that in this PR I transform the borderless table to a normal one before formatting it, so it gives the same result as before.

As for default value of the flag I'll let you decide. Right now it's disabled by default.

2023-11-01 18:19 UTC, alerque approved these changes
Oooo, now we're talking. Gated behind a default-off flag sounds better too me since the worry is with false positives messing people up when they aren't expecting this. Thanks especially for adding tests and docs!

2023-11-01 18:22 UTC, alerque commented
Would you like me to squash merge this or would you like to go through and split this up a little different? The current commit list isn't going to be very informative to a user updating through their plugin manager. One squashed `feat: ...` commit would be okay, or you can rebase (or I would use `git revise`) to spit out a feature commit for the range option and another for all the new tooling, then a doc commit for the help messages and a test one for the tests.

2023-11-01 18:55 UTC, gko commented
> Would you like me to squash merge this or would you like to go through and split this up a little different?

I think we can squash it if it's easier.

Thank you for maintaining this plugin ❤️

P.S. tested it on some complicated tables and it worked better than prettier

2023-11-01 20:22 UTC, merged

2023-11-01 20:23 UTC, alerque commented
@gka I'm not really maintaining this, I'm just around the org to facilitate community contributions actually landing. Feel free to jump in!